DeutscheModelUnitedNations/munify-chase

chase/frontend/public/flags/gbr.svg

branch: 35-united-kingdom-wrong-flag

🐞 fix (CHASE Frontend): Correct GBR flag

---

chase/backend/src/routes/delegation.ts
chase/frontend/app/app/[conferenceId]/committee/[committeeId]/chair/attendees/page.tsx
chase/frontend/i18n/de/index.ts
chase/frontend/i18n/en/index.ts
chase/frontend/i18n/i18n-types.ts

Co-authored-by: m1212e <m1212e@users.noreply.github.com>
branch: 90-möglichkeit-anwesenheitsliste-zurückzusetzen

✨ feat (CHASE Frontend): Buttons at presence page: Set all Preset/Absent

---

chase/frontend/i18n/de/index.ts

branch: 92-german-translation-in-menüs-statt-abbrechen-schließen-schreiben

⬆️ improvement (CHASE Frontend): Update cancel button label in addSpeakerOverlay

---

chase/frontend/app/app/[conferenceId]/committee/[committeeId]/(presentation-mode)/page.tsx
chase/frontend/components/dashboard/timer.tsx

branch: 94-better-responsiveness-for-presentation-mode

⬆️ improvement (CHASE Frontend): Better Presentation Mode Responsivness

---

chase/frontend/app/app/[conferenceId]/committee/[committeeId]/chair/inbox/page.tsx
chase/frontend/components/dashboard/actions.tsx
chase/frontend/components/dashboard/actions_overlay.tsx

branch: 98-enable-chairs-to-create-their-own-messages-for-wd

✨ feat (CHASE Frontend): Chairs can now generate their own messages for WD

---

chase/frontend/components/inbox/message_details.tsx
chase/frontend/i18n/de/index.ts
chase/frontend/i18n/en/index.ts
chase/frontend/i18n/i18n-types.ts

branch: 100-better-description-of-inbox-buttons-tooltips

⬆️ improvement (CHASE Frontend): Better description of inbox buttons (with tooltips and other icons)

---

chase/frontend/components/navbar/button.tsx

branch: 104-fix-external-links-in-navbar

🐞 fix (CHASE Frontend): External links in navbar are now opening in a new tab

---

chase/frontend/components/speakers_list/speech_buttons.tsx
chase/frontend/i18n/de/index.ts
chase/frontend/i18n/en/index.ts
chase/frontend/i18n/i18n-types.ts

branch: 105-better-independent-descriptions-for-next-speaker-prompts

⬆️ improvement (CHASE Frontend): Warning dialog to advance to next speaker now shows the type of list, so that it is not easily confused

---

chase/frontend/components/speakers_list/speaker_block.tsx

branch: 118-show-current-speaking-time-as-reference

✨ feat (CHASE Frontend): Add Speakers Time Reference and increase font size for Country and Speakers Time

---

chase/backend/prisma/migrations/20240317151124_change_placeholder_for_whiteboard/migration.sql
chase/backend/prisma/schema.prisma

branch: 120-change-whiteboard-default-text

✨ feat (CHASE Frontend): Update whiteboardContent default value to "Willkommen!"

---

chase/frontend/app/app/[conferenceId]/committee/[committeeId]/(presentation-mode)/page.tsx
chase/frontend/contexts/toast.tsx

branch: 115-surpress-toastsnotifications-on-presentation-view

🐞 fix (CHASE Frontend): add disable/enable toasts on certain pages (e.g. the presentation mode page)

---

chase/frontend/components/attendance/presence_widget.tsx

branch: 124-security-council-majority-edge-case

✨ feat (CHASE Frontend): Handle Security Council Edge Case, where the simple majority is always set to a static 9 votes, not 8 (15/2)

---

chase/backend/prisma/migrations/20240506102327_press_and_feedback_websites/migration.sql
chase/backend/prisma/schema.prisma
chase/backend/src/auth/abilities/abilities.ts
chase/backend/src/routes/baseData.ts
chase/frontend/app/app/[conferenceId]/admin/configs/page.tsx
chase/frontend/app/app/[conferenceId]/committee/[committeeId]/chair/layout.tsx
chase/frontend/app/app/[conferenceId]/committee/[committeeId]/participant/layout.tsx
chase/frontend/app/app/[conferenceId]/hub/team/layout.tsx
chase/frontend/components/navbar/external_links.tsx
chase/frontend/i18n/de/index.ts
chase/frontend/i18n/en/index.ts
chase/frontend/i18n/i18n-types.ts

branch: 148-right-press-site-for-munbw-2024

⬆️ improvement (App Frontend): Allow Admin to set and change press and feedback URLs

---

chase/frontend/app/app/[conferenceId]/committee/[committeeId]/chair/whiteboard/page.tsx

branch: 155-whiteboard-not-functioning

🐞 fix (App Frontend): Whiteboard not working

---

chase/frontend/components/speakers_list/speech_buttons.tsx

branch: 160-safety-modal-before-advancing-to-the-next-speaker-make-default-option-yes

✨ feat (App Frontend): Better Next Speaker Warning with "Yes" preselected

---

chase/frontend/app/app/[conferenceId]/committee/[committeeId]/chair/dashboard/page.tsx
chase/frontend/app/app/[conferenceId]/committee/[committeeId]/regional_groups/page.tsx
chase/frontend/components/dashboard/chair/regional_groups_lookup.tsx
chase/frontend/i18n/de/index.ts
chase/frontend/i18n/en/index.ts
chase/frontend/i18n/i18n-types.ts

branch: 164-add-regional-groups-lookup-for-chairs

✨ feat (App Frontend): Regional Groups Lookup for Chairs

---

.github/workflows/build.yml

🏗️ build (MUNify): add caches for bun dependencies

---

chase/frontend/components/cookie_banner.tsx

✨ feature: added black semi transparent backdrop for cookie banner

---

bun.lock
messages/de.json
src/routes/app/(launcher)/create/+page.svelte

Please go the the `Preview` tab and select the appropriate sub-template:
* [🐞 Bug Fix](?expand=1&labels=bug&title=🐞+fix%3a&template=empty.md)
* [🚀 Enhancement](?expand=1&labels=enhancement&title=🚀+enhancement%3a&template=empty.md)
* [✨ Feature](?expand=1&labels=feature&title=✨+feature%3a&template=empty.md)
* [📚 Documentation](?expand=1&labels=documentation&title=📚+documentation%3a&template=empty.md)

✨ feat: add file upload functionality for conference creation

---

src/lib/components/whiteboard/WhiteboardEditor.svelte
src/lib/components/whiteboard/WhiteboardViewer.svelte

🐞 fix: Update prose leading class for consistent text styling in Whiteboard

---

schema.graphql
src/api/db/relations.ts
src/api/handlers/agendaItem.ts
src/api/handlers/conference.ts
src/lib/components/speakersList/ChairSpeakersQueue.svelte
src/lib/helpers/distinguishConferenceMembers.ts
src/routes/app/(launcher)/+page.svelte
src/routes/app/(launcher)/import/+page.svelte
src/routes/app/[conferenceId]/[committeeId]/(chairs)/+layout.gql
src/routes/app/[conferenceId]/[committeeId]/(chairs)/committeeSubscription.ts
src/routes/app/[conferenceId]/[committeeId]/(chairs)/presence/+page.svelte
src/routes/app/[conferenceId]/[committeeId]/(presentation)/+page.gql
src/routes/app/[conferenceId]/[committeeId]/(presentation)/committeeSubscription.ts

Fixes https://github.com/DeutscheModelUnitedNations/munify-chase/issues/255

🐞 fix: unique NSA and UN entries

---

src/lib/components/speakersList/chairControls/AddSpeakers.svelte

@Strehk I am getting an error in VS code because conference member does not have a present variable, but the member has. As the getName does not use the variable anyway I am unsure how to fix the problem. We could also relax the requirement of the Get name function.

🐞 fix: #277
